version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      BASE_CONNECTION_STRING: postgre://pguser:pgpassword1234@localhost:5432/postgres

  postgre:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
