version: '3'

services:
  api:
    build: .
    ports:
      - 3000:3000
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
